import { IPinYinMapItem } from '../typings';

/**
 * 笔画键盘按钮
 */
export const STROKE_MAP = [
  { value: '一', label: '一' },
  { value: '丨', label: '丨' },
  { value: 'ノ', label: 'ノ' },
  { value: '丶', label: '丶' },
  { value: 'フ', label: 'フ' },
  { value: '*', label: '通配符', extraClassName: 'text-btn' },
];

/**
 * 拼音键盘按钮
 */
export const PINYIN_MAP: IPinYinMapItem[][] = [
  // 第一行
  [
    { label: 'Q', value: 'Q' },
    { label: 'W', value: 'W' },
    { label: 'E', value: 'E' },
    { label: 'R', value: 'R' },
    { label: 'T', value: 'T' },
    { label: 'Y', value: 'Y' },
    { label: 'U', value: 'U' },
    { label: 'I', value: 'I' },
    { label: 'O', value: 'O' },
    { label: 'P', value: 'P' },
  ],
  // 第二行
  [
    { label: 'A', value: 'A' },
    { label: 'S', value: 'S' },
    { label: 'D', value: 'D' },
    { label: 'F', value: 'F' },
    { label: 'G', value: 'G' },
    { label: 'H', value: 'H' },
    { label: 'J', value: 'J' },
    { label: 'K', value: 'K' },
    { label: 'L', value: 'L' },
  ],
  // 第三行
  [
    { label: 'Z', value: 'Z' },
    { label: 'X', value: 'X' },
    { label: 'C', value: 'C' },
    { label: 'V', value: 'V' },
    { label: 'B', value: 'B' },
    { label: 'N', value: 'N' },
    { label: 'M', value: 'M' },
  ],
];

export const SPLIT_MAP = [
  {
    category: '一画',
    words: [
      { label: '一', value: '一' },
      { label: '丨', value: '丨' },
      { label: '丿', value: '丿' },
      { label: '丶', value: '丶' },
      { label: '乛', value: '乛' },
      { label: '亅', value: '亅' },
      { label: '乚', value: '乚' },
      { label: '乙', value: '乙' },
    ],
  },
  {
    category: '二画',
    words: [
      { label: '十', value: '十' },
      { label: '厂', value: '厂' },
      { label: '𠂆', value: '𠂆' },
      { label: '匚', value: '匚' },
      { label: '卜', value: '卜' },
      { label: '⺊', value: '⺊' },
      { label: '冂', value: '冂' },
      { label: '⺆', value: '⺆' },
      { label: '八', value: '八' },
      { label: '丷', value: '丷' },
      { label: '人', value: '人' },
      { label: '亻', value: '亻' },
      { label: '入', value: '入' },
      { label: '勹', value: '勹' },
      { label: '儿', value: '儿' },
      { label: '匕', value: '匕' },
      { label: '几', value: '几' },
      { label: '𠘨', value: '𠘨' },
      { label: '亠', value: '亠' },
      { label: '冫', value: '冫' },
      { label: '冖', value: '冖' },
      { label: '凵', value: '凵' },
      { label: '卩', value: '卩' },
      { label: '㔾', value: '㔾' },
      { label: '刀', value: '刀' },
      { label: '刂', value: '刂' },
      { label: '⺈', value: '⺈' },
      { label: '力', value: '力' },
      { label: '又', value: '又' },
      { label: '厶', value: '厶' },
      { label: '廴', value: '廴' },
    ],
  },
  {
    category: '三画',
    words: [
      { label: '干', value: '干' },
      { label: '工', value: '工' },
      { label: '土', value: '土' },
      { label: '士', value: '士' },
      { label: '艹', value: '艹' },
      { label: '艸', value: '艸' },
      { label: '寸', value: '寸' },
      { label: '廾', value: '廾' },
      { label: '大', value: '大' },
      { label: '尢', value: '尢' },
      { label: '兀', value: '兀' },
      { label: '尣', value: '尣' },
      { label: '弋', value: '弋' },
      { label: '小', value: '小' },
      { label: '⺌', value: '⺌' },
      { label: '口', value: '口' },
      { label: '囗', value: '囗' },
      { label: '山', value: '山' },
      { label: '巾', value: '巾' },
      { label: '彳', value: '彳' },
      { label: '彡', value: '彡' },
      { label: '夕', value: '夕' },
      { label: '夂', value: '夂' },
      { label: '丬', value: '丬' },
      { label: '爿', value: '爿' },
      { label: '广', value: '广' },
      { label: '门', value: '门' },
      { label: '門', value: '門' },
      { label: '宀', value: '宀' },
      { label: '辶', value: '辶' },
      { label: '辵', value: '辵' },
      { label: '彐', value: '彐' },
      { label: '⺕', value: '⺕' },
      { label: '彑', value: '彑' },
      { label: '尸', value: '尸' },
      { label: '己', value: '己' },
      { label: '已', value: '已' },
      { label: '巳', value: '巳' },
      { label: '弓', value: '弓' },
      { label: '子', value: '子' },
      { label: '屮', value: '屮' },
      { label: '女', value: '女' },
      { label: '飞', value: '飞' },
      { label: '飛', value: '飛' },
      { label: '马', value: '马' },
      { label: '馬', value: '馬' },
      { label: '幺', value: '幺' },
      { label: '巛', value: '巛' },
    ],
  },
  {
    category: '四画',
    words: [
      { label: '王', value: '王' },
      { label: '𤣩', value: '𤣩' },
      { label: '玉', value: '玉' },
      { label: '无', value: '无' },
      { label: '旡', value: '旡' },
      { label: '韦', value: '韦' },
      { label: '韋', value: '韋' },
      { label: '木', value: '木' },
      { label: '朩', value: '朩' },
      { label: '支', value: '支' },
      { label: '犬', value: '犬' },
      { label: '犭', value: '犭' },
      { label: '歹', value: '歹' },
      { label: '歺', value: '歺' },
      { label: '车', value: '车' },
      { label: '車', value: '車' },
      { label: '牙', value: '牙' },
      { label: '戈', value: '戈' },
      { label: '比', value: '比' },
      { label: '瓦', value: '瓦' },
      { label: '止', value: '止' },
      { label: '攴', value: '攴' },
      { label: '攵', value: '攵' },
      { label: '日', value: '日' },
      { label: '曰', value: '曰' },
      { label: '⺜', value: '⺜' },
      { label: '贝', value: '贝' },
      { label: '貝', value: '貝' },
      { label: '水', value: '水' },
      { label: '氵', value: '氵' },
      { label: '氺', value: '氺' },
      { label: '见', value: '见' },
      { label: '見', value: '見' },
      { label: '牛', value: '牛' },
      { label: '牜', value: '牜' },
      { label: '手', value: '手' },
      { label: '扌', value: '扌' },
      { label: '龵', value: '龵' },
      { label: '气', value: '气' },
      { label: '毛', value: '毛' },
      { label: '长', value: '长' },
      { label: '镸', value: '镸' },
      { label: '長', value: '長' },
      { label: '片', value: '片' },
      { label: '斤', value: '斤' },
      { label: '爪', value: '爪' },
      { label: '爫', value: '爫' },
      { label: '父', value: '父' },
      { label: '月', value: '月' },
      { label: '⺝', value: '⺝' },
      { label: '氏', value: '氏' },
      { label: '欠', value: '欠' },
      { label: '风', value: '风' },
      { label: '風', value: '風' },
      { label: '殳', value: '殳' },
      { label: '文', value: '文' },
      { label: '方', value: '方' },
      { label: '火', value: '火' },
      { label: '灬', value: '灬' },
      { label: '斗', value: '斗' },
      { label: '户', value: '户' },
      { label: '心', value: '心' },
      { label: '忄', value: '忄' },
      { label: '⺗', value: '⺗' },
      { label: '毋', value: '毋' },
      { label: '母', value: '母' },
    ],
  },
  {
    category: '五画',
    words: [
      { label: '示', value: '示' },
      { label: '礻', value: '礻' },
      { label: '甘', value: '甘' },
      { label: '石', value: '石' },
      { label: '龙', value: '龙' },
      { label: '龍', value: '龍' },
      { label: '业', value: '业' },
      { label: '目', value: '目' },
      { label: '田', value: '田' },
      { label: '罒', value: '罒' },
      { label: '皿', value: '皿' },
      { label: '生', value: '生' },
      { label: '矢', value: '矢' },
      { label: '禾', value: '禾' },
      { label: '白', value: '白' },
      { label: '瓜', value: '瓜' },
      { label: '鸟', value: '鸟' },
      { label: '鳥', value: '鳥' },
      { label: '疒', value: '疒' },
      { label: '立', value: '立' },
      { label: '穴', value: '穴' },
      { label: '疋', value: '疋' },
      { label: '𤴔', value: '𤴔' },
      { label: '皮', value: '皮' },
      { label: '癶', value: '癶' },
      { label: '矛', value: '矛' },
    ],
  },
  {
    category: '六画',
    words: [
      { label: '耒', value: '耒' },
      { label: '老', value: '老' },
      { label: '耂', value: '耂' },
      { label: '耳', value: '耳' },
      { label: '臣', value: '臣' },
      { label: '覀', value: '覀' },
      { label: '西', value: '西' },
      { label: '而', value: '而' },
      { label: '页', value: '页' },
      { label: '頁', value: '頁' },
      { label: '至', value: '至' },
      { label: '虍', value: '虍' },
      { label: '虎', value: '虎' },
      { label: '虫', value: '虫' },
      { label: '肉', value: '肉' },
      { label: '缶', value: '缶' },
      { label: '舌', value: '舌' },
      { label: '竹', value: '竹' },
      { label: '𥫗', value: '𥫗' },
      { label: '臼', value: '臼' },
      { label: '自', value: '自' },
      { label: '血', value: '血' },
      { label: '舟', value: '舟' },
      { label: '色', value: '色' },
      { label: '齐', value: '齐' },
      { label: '齊', value: '齊' },
      { label: '衣', value: '衣' },
      { label: '衤', value: '衤' },
      { label: '羊', value: '羊' },
      { label: '⺶', value: '⺶' },
      { label: '𦍌', value: '𦍌' },
      { label: '米', value: '米' },
      { label: '聿', value: '聿' },
      { label: '肀', value: '肀' },
      { label: '⺻', value: '⺻' },
      { label: '艮', value: '艮' },
      { label: '羽', value: '羽' },
      { label: '糸', value: '糸' },
      { label: '纟', value: '纟' },
      { label: '糹', value: '糹' },
    ],
  },
  {
    category: '七画',
    words: [
      { label: '麦', value: '麦' },
      { label: '麥', value: '麥' },
      { label: '走', value: '走' },
      { label: '赤', value: '赤' },
      { label: '豆', value: '豆' },
      { label: '酉', value: '酉' },
      { label: '辰', value: '辰' },
      { label: '豕', value: '豕' },
      { label: '卤', value: '卤' },
      { label: '鹵', value: '鹵' },
      { label: '里', value: '里' },
      { label: '足', value: '足' },
      { label: '𧾷', value: '𧾷' },
      { label: '邑', value: '邑' },
      { label: '⻏', value: '⻏' },
      { label: '在', value: '在' },
      { label: '右', value: '右' },
      { label: '身', value: '身' },
      { label: '釆', value: '釆' },
      { label: '谷', value: '谷' },
      { label: '豸', value: '豸' },
      { label: '龟', value: '龟' },
      { label: '龜', value: '龜' },
      { label: '角', value: '角' },
      { label: '言', value: '言' },
      { label: '讠', value: '讠' },
      { label: '辛', value: '辛' },
    ],
  },
  {
    category: '八画',
    words: [
      { label: '青', value: '青' },
      { label: '龺', value: '龺' },
      { label: '雨', value: '雨' },
      { label: '⻗', value: '⻗' },
      { label: '非', value: '非' },
      { label: '齿', value: '齿' },
      { label: '齒', value: '齒' },
      { label: '黾', value: '黾' },
      { label: '黽', value: '黽' },
      { label: '隹', value: '隹' },
      { label: '阜', value: '阜' },
      { label: '⻖', value: '⻖' },
      { label: '在', value: '在' },
      { label: '左', value: '左' },
      { label: '金', value: '金' },
      { label: '钅', value: '钅' },
      { label: '鱼', value: '鱼' },
      { label: '魚', value: '魚' },
      { label: '隶', value: '隶' },
    ],
  },
  {
    category: '九画',
    words: [
      { label: '革', value: '革' },
      { label: '面', value: '面' },
      { label: '韭', value: '韭' },
      { label: '骨', value: '骨' },
      { label: '香', value: '香' },
      { label: '鬼', value: '鬼' },
      { label: '食', value: '食' },
      { label: '饣', value: '饣' },
      { label: '飠', value: '飠' },
      { label: '音', value: '音' },
      { label: '首', value: '首' },
    ],
  },
  {
    category: '十画',
    words: [
      { label: '髟', value: '髟' },
      { label: '鬲', value: '鬲' },
      { label: '鬥', value: '鬥' },
      { label: '高', value: '高' },
    ],
  },
  {
    category: '十一画',
    words: [
      { label: '黄', value: '黄' },
      { label: '麻', value: '麻' },
      { label: '鹿', value: '鹿' },
    ],
  },
  {
    category: '十二画',
    words: [
      { label: '鼎', value: '鼎' },
      { label: '黑', value: '黑' },
      { label: '黍', value: '黍' },
    ],
  },
  {
    category: '十三画',
    words: [
      { label: '鼓', value: '鼓' },
      { label: '鼠', value: '鼠' },
    ],
  },
  { category: '十四画', words: [{ label: '鼻', value: '鼻' }] },
  { category: '十七画', words: [{ label: '龠', value: '龠' }] },
];

export const BTN_TEXT = {
  SYMBOL: '符',
  RETRY: '重试',
  CONFIRM: '确认',
};
